### ISSUE TITLE
Separate theory and implementation in documentation

### ISSUE THREAD

**Issue by DanielStenis** [afconsult-south/dragonfly-fcb#124]
Perhaps it's a good idea to have separate documents on theory and code design and implementation.

Theory:
- Flight dynamics (coordinate systems, system equations etc.)
- Flight control
- Estimation theory
- Motor theory
- Sensor theory
- Experiments

Implemenation:
- Code design
- UML diagrams
- Real-time diagrams on running tasks etc.

**Comment by adam-at-epsilon** [comment]
The only difficulty I can foresee with having two documents is the usability of the documentation on the part of the reader.

If we have one document, we can click cross-references back and forth between theory and implementation, if we have two different documents this back-and-forth clicking is not possible because links in PDF cannot open other PDF documents as far as I'm aware.

**Comment by DanielStenis** [comment]
I guess.

But regardless it would generally be nice to separate these theory and implementation. Perhaps in chapters then.

**Comment by adam-at-epsilon** [comment]
Yes I agree they should be separate chapters. If the documents get too big & unwieldy to edit & maintain perhaps we should split them into separates.

**Comment by DanielStenis** [comment]
Then maybe this is a non-issue at this moment in time. Closing.
